#
# site settings
#
title: Triple Except
description: Discussions from all depths of computer science

excerpt_separator: <!--more-->

#
# build setting
#
markdown: kramdown
safe: true

kramdown:
        # Use Github-flavoured markdown (e.g. triple backtick code)
        input: GFM
        syntax_highlighter: rouge

        syntax_highlighter_opts:
                span:
                        line_numbers: false
                block:
                        line_numbers: true
                        start_line: 1

# Sass generated css
sass:
        style: expanded


# Use the following plug-ins
plugins:
        - jekyll-sitemap # Create a sitemap
        - jekyll-feed # Create an Atom feed

# Exclude these files from production
exclude:
        - LICENSE
        - README.md
        - Dockerfile
        - Makefile

# vim: set et ts=8 sw=8:
